export enum ENV {
  APP_NAME = 'APP_NAME',
  APP_ENV = 'APP_ENV',
  IS_DEV = 'IS_DEV',
  IS_STG = 'IS_STG',
  IS_PRD = 'IS_PRD',
  IS_TEST = 'IS_TEST',
  APP_PORT = 'APP_PORT',
  WORKER_PORT = 'WORKER_PORT',
  USER_SECRET = 'USER_SECRET',
  USER_TOKEN_EXPIRE_IN = 'USER_TOKEN_EXPIRE_IN',
  USER_REFRESH_SECRET = 'USER_REFRESH_SECRET',
  USER_REFRESH_TOKEN_EXPIRE_IN = 'USER_REFRESH_TOKEN_EXPIRE_IN',
  ADMIN_SECRET = 'ADMIN_SECRET',
  ADMIN_TOKEN_EXPIRE_IN = 'ADMIN_TOKEN_EXPIRE_IN',
  ADMIN_REFRESH_SECRET = 'ADMIN_REFRESH_SECRET',
  ADMIN_REFRESH_TOKEN_EXPIRE_IN = 'ADMIN_REFRESH_TOKEN_EXPIRE_IN',

  DATABASE_URL = 'DATABASE_URL',

  CACHE_MODE = 'CACHE_MODE',
  CACHE_TTL = 'CACHE_TTL',

  USE_QUEUE = 'USE_QUEUE',

  REDIS_MODE = 'REDIS_MODE',
  REDIS_URL = 'REDIS_URL',

  LOGGER_TYPE = 'LOGGER_TYPE',
  LOGGER_MAX_FILES = 'LOGGER_MAX_FILES',
  LOGGER_LEVEL = 'LOGGER_LEVEL',
  LOGGER_DATABASE_URL = 'LOGGER_DATABASE_URL',

  UPLOAD_PATH = 'UPLOAD_PATH',
  BODY_SIZE = 'BODY_SIZE',

  SWAGGER_TITLE = 'SWAGGER_TITLE',
  SWAGGER_DESCRIPTION = 'SWAGGER_DESCRIPTION',
  SWAGGER_VERSION = 'SWAGGER_VERSION',
  SWAGGER_FAVICON = 'SWAGGER_FAVICON',
  SWAGGER_ENDPOINT = 'SWAGGER_ENDPOINT',
}

export enum CACHE_TYPE {
  REDIS = 'redis',
  MEMORY = 'memory',
}

export enum LOGGER_TYPE {
  WINSTON = 'winston',
}

export enum APP_ENV {
  DEV = 'dev',
  STG = 'stg',
  PRD = 'prd',
  TEST = 'test',
}
